---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: revest
  namespace: dev
  labels:
    env: dev
    project: devops
spec:
  minReadySeconds: 20
  replicas: 2
  selector:
    matchLabels:
      app: revest
  template:
    metadata:
      labels:
        app: revest
    spec:
      containers:
      - name: revest
        image: 888577027777.dkr.ecr.ap-south-1.amazonaws.com/dev/revest:latest
        ports:
          - containerPort: 80    
        resources:
          requests:
            memory: "128Mi"         
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        env:
            - name: DB_HOST
              value: "mysql-service.kube-system.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret  
                  key: db-username    
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret  
                  key: db-password   
        startupProbe:               
          exec:
            command:
              - pwd
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1  
          failureThreshold: 2  
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1  
          failureThreshold: 2  
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1  
          failureThreshold: 2  
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets"
            readOnly: true
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
