---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  POSTGRES_DB: mydb
  POSTGRES_HOST: postgres.default.svc.cluster.local
  POSTGRES_PORT: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: revest-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: revest
  template:
    metadata:
      labels:
        app: revest
    spec:
      containers:
        - name: revest
          image: 888577027777.dkr.ecr.ap-south-1.amazonaws.com/dev/revest:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
      imagePullSecrets:
        - name: ecr-creds
---
apiVersion: v1
kind: Service
metadata:
  name: revest-service
spec:
  selector:
    app: revest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080